"""
AgentTeam Init Command - Interactive Onboarding Wizard

Provides a guided 5-step setup experience for new users:
1. Check Python version (>= 3.10)
2. Select backend (claude-code / codex / openclaw / custom)
3. Configure database path
4. Configure transport (file / p2p / redis)
5. Write config and show success summary
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Optional

try:
    import questionary
    from questionary import Choice, prompt

    QUESTIONARY_AVAILABLE = True
except ImportError:
    QUESTIONARY_AVAILABLE = False

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

from agentteam import __version__

app = typer.Typer(
    name="init",
    help="Initialize AgentTeam with interactive setup wizard",
    no_args_is_help=False,
)
console = Console()

# Config file location
CONFIG_DIR = Path.home() / ".agentteam"
CONFIG_FILE = CONFIG_DIR / "config.yaml"

# Default backend options
BACKEND_OPTIONS = [
    {"id": "claude-code", "name": "Claude Code", "desc": "Anthropic's Claude CLI agent"},
    {"id": "codex", "name": "OpenAI Codex", "desc": "OpenAI's code agent (claude-code compatible)"},
    {"id": "openclaw", "name": "OpenClaw", "desc": "Generic agent with SDK support"},
    {"id": "custom", "name": "Custom", "desc": "Define your own agent backend"},
]

# Transport options
TRANSPORT_OPTIONS = [
    {"id": "file", "name": "File-based", "desc": "JSON file storage (simple, no dependencies)"},
    {"id": "p2p", "name": "P2P (ZMQ)", "desc": "Peer-to-peer messaging via ZeroMQ"},
    {"id": "redis", "name": "Redis", "desc": "Redis pub/sub for distributed systems"},
]


def check_python_version() -> tuple[bool, str]:
    """Check if Python version meets requirements (>= 3.10)."""
    version = sys.version_info
    if version.major == 3 and version.minor >= 10:
        return True, f"Python {version.major}.{version.minor}.{version.micro} ✓"
    return False, f"Python {version.major}.{version.minor}.{version.micro} - requires >= 3.10"


def get_default_data_dir() -> Path:
    """Get the default data directory."""
    return Path.home() / ".agentteam"


def get_config_value(config: dict, key: str, default: str) -> str:
    """Safely get config value."""
    parts = key.split(".")
    value = config
    for part in parts:
        if isinstance(value, dict):
            value = value.get(part, default)
        else:
            return default
    return value if value else default


def generate_config_content(
    backend: str,
    database_path: str,
    transport: str,
    custom_backend_path: Optional[str] = None,
) -> str:
    """Generate YAML config content."""
    content = f"""# AgentTeam Configuration
# Generated by `agentteam init` v{__version__}

version: "{__version__}"

# Agent Backend Configuration
backend:
  type: "{backend}"
  {'custom_path: "' + custom_backend_path + '"' if custom_backend_path and backend == "custom" else ""}

# Database Configuration
database:
  path: "{database_path}"
  
# Transport Configuration
transport:
  type: "{transport}"
  
# Optional: Advanced Settings
# Uncomment and modify as needed

# logging:
#   level: "INFO"
#   format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# metrics:
#   enabled: true
#   port: 9090

# telemetry:
#   enabled: false
#   endpoint: "http://localhost:4317"
"""
    return content.strip()


def write_config(content: str) -> tuple[bool, str]:
    """Write config file to disk."""
    try:
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            f.write(content)
        return True, str(CONFIG_FILE)
    except Exception as e:
        return False, str(e)


def show_success_summary(
    backend: str,
    database_path: str,
    transport: str,
    config_path: str,
) -> None:
    """Display success summary in a rich panel."""
    table = Table(title="✓ Setup Complete!", show_header=False, box=None)
    table.add_column("Key", style="bold cyan")
    table.add_column("Value", style="green")

    table.add_row("Backend", backend)
    table.add_row("Database", database_path)
    table.add_row("Transport", transport)
    table.add_row("Config File", config_path)

    panel = Panel(
        table,
        title="[bold green]AgentTeam Initialization Successful[/bold green]",
        border_style="green",
    )
    console.print(panel)

    console.print("\n[bold]Next steps:[/bold]")
    console.print("  1. Run [cyan]agentteam team create[/cyan] to create your first team")
    console.print("  2. Run [cyan]agentteam board serve[/cyan] to start the dashboard")
    console.print("  3. Run [cyan]agentteam --help[/cyan] to see all commands")


def run_wizard_questionary() -> Optional[dict]:
    """Run the interactive wizard using questionary."""
    if not QUESTIONARY_AVAILABLE:
        return None

    questions = [
        {
            "type": "confirm",
            "name": "proceed",
            "message": "Welcome to AgentTeam! Ready to set up your environment?",
            "default": True,
        },
        {
            "type": "select",
            "name": "backend",
            "message": "Select your agent backend:",
            "choices": [Choice(title=f"{b['name']} - {b['desc']}", value=b["id"]) for b in BACKEND_OPTIONS],
            "default": "claude-code",
        },
        {
            "type": "input",
            "name": "custom_backend",
            "message": "Enter custom backend path (optional):",
            "when": lambda x: x.get("backend") == "custom",
        },
        {
            "type": "input",
            "name": "database_path",
            "message": "Enter database path:",
            "default": str(get_default_data_dir() / "data.db"),
        },
        {
            "type": "select",
            "name": "transport",
            "message": "Select transport backend:",
            "choices": [Choice(title=f"{t['name']} - {t['desc']}", value=t["id"]) for t in TRANSPORT_OPTIONS],
            "default": "file",
        },
        {
            "type": "confirm",
            "name": "confirm",
            "message": "Ready to write configuration?",
            "default": True,
        },
    ]

    answers = prompt(questions)
    return answers


def run_wizard_manual() -> Optional[dict]:
    """Run the interactive wizard using rich prompts (fallback)."""
    console.print(
        Panel.fit(
            "[bold green]AgentTeam Init Wizard[/bold green]\nFollow the prompts to configure your environment.",
            border_style="green",
        )
    )
    console.print()

    # Step 0: Welcome
    proceed = console.input("[bold cyan]Proceed with setup?[/bold cyan] [Y/n]: ").strip().lower()
    if proceed == "n":
        console.print("[yellow]Setup cancelled.[/yellow]")
        return None

    # Step 1: Backend selection
    console.print("\n[bold]Step 1: Select Backend[/bold]")
    for i, b in enumerate(BACKEND_OPTIONS, 1):
        console.print(f"  {i}. {b['name']} - {b['desc']}")

    backend_choice = console.input("Enter choice [1-4] (default: 1): ").strip()
    if not backend_choice:
        backend_choice = "1"

    try:
        backend_idx = int(backend_choice) - 1
        backend = BACKEND_OPTIONS[backend_idx]["id"]
    except (ValueError, IndexError):
        backend = "claude-code"

    # Custom backend path
    custom_backend_path = None
    if backend == "custom":
        custom_backend_path = console.input("  Enter custom backend path: ").strip()

    # Step 2: Database path
    console.print("\n[bold]Step 2: Database Path[/bold]")
    default_db = get_default_data_dir() / "data.db"
    database_path = console.input(f"Enter path [{default_db}]: ").strip()
    if not database_path:
        database_path = str(default_db)

    # Step 3: Transport selection
    console.print("\n[bold]Step 3: Select Transport[/bold]")
    for i, t in enumerate(TRANSPORT_OPTIONS, 1):
        console.print(f"  {i}. {t['name']} - {t['desc']}")

    transport_choice = console.input("Enter choice [1-3] (default: 1): ").strip()
    if not transport_choice:
        transport_choice = "1"

    try:
        transport_idx = int(transport_choice) - 1
        transport = TRANSPORT_OPTIONS[transport_idx]["id"]
    except (ValueError, IndexError):
        transport = "file"

    # Step 4: Confirm and write
    console.print("\n[bold]Step 4: Summary[/bold]")
    console.print(f"  Backend: {backend}")
    if custom_backend_path:
        console.print(f"  Custom Backend Path: {custom_backend_path}")
    console.print(f"  Database: {database_path}")
    console.print(f"  Transport: {transport}")

    confirm = console.input("\nWrite config? [Y/n]: ").strip().lower()
    if confirm == "n":
        console.print("[yellow]Setup cancelled.[/yellow]")
        return None

    return {
        "backend": backend,
        "custom_backend": custom_backend_path,
        "database_path": database_path,
        "transport": transport,
    }


@app.command()
def init(
    backend: str = typer.Option(
        None,
        "--backend",
        "-b",
        help="Backend type: claude-code, codex, openclaw, custom",
    ),
    database_path: str = typer.Option(
        None,
        "--database",
        "-d",
        help="Database file path",
    ),
    transport: str = typer.Option(
        None,
        "--transport",
        "-t",
        help="Transport type: file, p2p, redis",
    ),
    custom_backend: str = typer.Option(
        None,
        "--custom-backend",
        help="Custom backend path (used with --backend custom)",
    ),
    non_interactive: bool = typer.Option(
        False,
        "--non-interactive",
        "-y",
        help="Use defaults without prompting",
    ),
) -> None:
    """
    Initialize AgentTeam with interactive setup wizard.

    This command guides you through 5 steps:
    1. Python version check
    2. Backend selection
    3. Database configuration
    4. Transport selection
    5. Config file generation

    Examples:
        agentteam init                    # Interactive wizard
        agentteam init --non-interactive # Use all defaults
        agentteam init -b claude-code   # Pre-select backend
    """
    console.print(
        Panel.fit(
            f"[bold green]AgentTeam v{__version__} - Setup Wizard[/bold green]\nLet's configure your environment!",
            border_style="bright_blue",
        )
    )
    console.print()

    # Step 0: Check Python version
    console.print("[bold]Step 0: System Check[/bold]")
    python_ok, python_msg = check_python_version()
    if python_ok:
        console.print(f"  {python_msg}")
    else:
        console.print(f"  [red]✗ {python_msg}[/red]")
        console.print("\n[bold red]Error: Python 3.10+ is required.[/bold red]")
        console.print("  Please upgrade Python and try again.")
        raise typer.Exit(code=1)
    console.print()

    # Step 1: Backend
    if backend is None:
        if non_interactive:
            backend = "claude-code"
        else:
            if QUESTIONARY_AVAILABLE:
                result = run_wizard_questionary()
            else:
                result = run_wizard_manual()

            if result is None:
                raise typer.Exit()

            backend = result.get("backend", "claude-code")
            custom_backend = result.get("custom_backend")
            database_path = result.get("database_path")
            transport = result.get("transport", "file")

    # Validate backend
    valid_backends = [b["id"] for b in BACKEND_OPTIONS]
    if backend not in valid_backends:
        console.print(f"[red]Invalid backend: {backend}[/red]")
        console.print(f"Valid options: {', '.join(valid_backends)}")
        raise typer.Exit(code=1)

    # Step 2: Database path
    if database_path is None:
        database_path = str(get_default_data_dir() / "data.db")

    # Step 3: Transport
    if transport is None:
        transport = "file"

    valid_transports = [t["id"] for t in TRANSPORT_OPTIONS]
    if transport not in valid_transports:
        console.print(f"[red]Invalid transport: {transport}[/red]")
        console.print(f"Valid options: {', '.join(valid_transports)}")
        raise typer.Exit(code=1)

    # Step 4: Show summary
    console.print("[bold]Step 4: Configuration Summary[/bold]")
    table = Table(show_header=False, box=None)
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")
    table.add_row("Backend", backend)
    if custom_backend and backend == "custom":
        table.add_row("Custom Path", custom_backend)
    table.add_row("Database", database_path)
    table.add_row("Transport", transport)
    console.print(table)
    console.print()

    # Step 5: Write config
    console.print("[bold]Step 5: Writing Config[/bold]")

    config_content = generate_config_content(
        backend=backend,
        database_path=database_path,
        transport=transport,
        custom_backend_path=custom_backend if backend == "custom" else None,
    )

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        progress.add_task("Writing config file...", total=None)
        success, result = write_config(config_content)

    if success:
        console.print(f"  [green]✓ Config written to: {result}[/green]")
    else:
        console.print(f"  [red]✗ Failed to write config: {result}[/red]")
        raise typer.Exit(code=1)

    # Show success summary
    console.print()
    show_success_summary(
        backend=backend,
        database_path=database_path,
        transport=transport,
        config_path=str(CONFIG_FILE),
    )


if __name__ == "__main__":
    app()
